/*スニペットのモジュールディレクトリを取得する

返値	スニペットのモジュールディレクトリを文字列で返しますが、
		処理に失敗すると空白文字を返します。
		
		(返値の例) c:\hidemaru-macro\ya-hidemaru-snippets\modules
		パス末尾にディレクトリ区切り(\/)は付きません。
*/
$path=currentmacrodirectory+"\\..\\snippets\\modules";
#obj=createobject("Scripting.FileSystemObject");
if(#obj==0){
	endmacro "";
}
$f = callmethod_returnstr( #obj, "GetAbsolutePathName", $path);
if(getresultex(10)==false){
	releaseobject #obj;
	endmacro "";
}
releaseobject #obj;
endmacro $f;