/*田楽DLLをロードする
*/

#g_dll_dengaku=loaddll(macrodir + "\\DengakuDLL.dll");
if (#g_dll_dengaku!=0) {
	endmacro str(#g_dll_dengaku);
}
#g_dll_dengaku=loaddll(hidemarudir + "\\DengakuDLL.dll");
if(#g_dll_dengaku==0){
	message
		"田楽DLLの読み込みに失敗しました。\n"	+
		"秀丸マクロディレクトリ、または、秀丸エディタのフォルダに田楽DLLが存在するか確認してください\n"	+
		"\n"	+
		"（秀丸マクロディレクトリ）\n"+
		macrodir+"\n"+
		"\n"+
		"（秀丸エディタ）\n"+
		hidemarudir+"\n";
}

endmacro str(#g_dll_dengaku);
